### ISSUE TITLE
spin_angular_momentum

### ISSUE THREAD

**Issue by kol66** [Double-Jiang-alpha/optical-force#2]
你好，请问这个文件的密码可以提供吗？
[spin_angular_momentum.pdf](https://github.com/user-attachments/files/15949232/spin_angular_momentum.pdf)

**Comment by Double-Jiang-alpha** [comment]
印象中，在read me 里面是有的，你可以看一下

2024-06-24 11:00:54kol66 ***@***.***>写道：

你好，请问这个文件的密码可以提供吗？
spin_angular_momentum.pdf

**Comment by kol66** [comment]
好的，我看到了，谢谢。我是一名研二的学生，目前在做关于optical forces and torques 结合 deep learning的学习。

**Comment by Double-Jiang-alpha** [comment]
这些和光力相关的PDF应该是我大三上的时候编写的，现在由于一部分原因我要转行做量子计算与量子信息了，希望这些以前组会汇报的notes对你有用。With best wishes!

2024-06-24 11:25:45kol66 ***@***.***>写道：

好的，我看到了，谢谢。我是一名研二的学生，目前在做关于optical forces and torques 结合 deep learning的学习。

**Comment by Double-Jiang-alpha** [comment]
在今年应该还会更新一部分和optical gradient force相关的工作（本科导师那边的项目），也会同步跟新Github,最近在准备保研的事情，预计八月份会跟新，我也会将我知道的与optical torques相关的也简单描述一下写进去，做完之后github上估计以后跟新的更多是与量子计算与量子信息、数学有关的内容了

2024-06-24 11:25:45kol66 ***@***.***>写道：

好的，我看到了，谢谢。我是一名研二的学生，目前在做关于optical forces and torques 结合 deep learning的学习。

**Comment by kol66** [comment]
好滴！我follow您了。期待您的更新。



在 2024-06-24 12:26:48，"Double-Jiang-alpha" ***@***.***> 写道：

在今年应该还会更新一部分和optical gradient force相关的工作（本科导师那边的项目），也会同步跟新Github,最近在准备保研的事情，预计八月份会跟新，我也会将我知道的与optical torques相关的也简单描述一下写进去，做完之后github上估计以后跟新的更多是与量子计算与量子信息、数学有关的内容了

2024-06-24 11:25:45kol66 ***@***.***>写道：

好的，我看到了，谢谢。我是一名研二的学生，目前在做关于optical forces and torques 结合 deep learning的学习。
